/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutmainImport } from './routes/_layoutmain'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutmainSoglIndexImport } from './routes/_layoutmain/sogl/index'
import { Route as LayoutmainRegIndexImport } from './routes/_layoutmain/reg/index'
import { Route as LayoutmainProfileIndexImport } from './routes/_layoutmain/profile/index'
import { Route as LayoutmainPayIndexImport } from './routes/_layoutmain/pay/index'
import { Route as LayoutmainOformlenieIndexImport } from './routes/_layoutmain/oformlenie/index'
import { Route as LayoutmainOfertaIndexImport } from './routes/_layoutmain/oferta/index'
import { Route as LayoutmainDostavkaIndexImport } from './routes/_layoutmain/dostavka/index'
import { Route as LayoutmainContactsIndexImport } from './routes/_layoutmain/contacts/index'
import { Route as LayoutmainConfidIndexImport } from './routes/_layoutmain/confid/index'
import { Route as LayoutmainCatalogIndexImport } from './routes/_layoutmain/catalog/index'
import { Route as LayoutmainCarzinaIndexImport } from './routes/_layoutmain/carzina/index'
import { Route as LayoutmainBrendsIndexImport } from './routes/_layoutmain/brends/index'
import { Route as LayoutmainAuthIndexImport } from './routes/_layoutmain/auth/index'
import { Route as LayoutmainAdminIndexImport } from './routes/_layoutmain/admin/index'
import { Route as LayoutmainAboutUsIndexImport } from './routes/_layoutmain/aboutUs/index'
import { Route as LayoutmainCardinfoCardInfoImport } from './routes/_layoutmain/cardinfo/cardInfo'

// Create/Update Routes

const LayoutmainRoute = LayoutmainImport.update({
  id: '/_layoutmain',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutmainSoglIndexRoute = LayoutmainSoglIndexImport.update({
  id: '/sogl/',
  path: '/sogl/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainRegIndexRoute = LayoutmainRegIndexImport.update({
  id: '/reg/',
  path: '/reg/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainProfileIndexRoute = LayoutmainProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainPayIndexRoute = LayoutmainPayIndexImport.update({
  id: '/pay/',
  path: '/pay/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainOformlenieIndexRoute = LayoutmainOformlenieIndexImport.update({
  id: '/oformlenie/',
  path: '/oformlenie/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainOfertaIndexRoute = LayoutmainOfertaIndexImport.update({
  id: '/oferta/',
  path: '/oferta/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainDostavkaIndexRoute = LayoutmainDostavkaIndexImport.update({
  id: '/dostavka/',
  path: '/dostavka/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainContactsIndexRoute = LayoutmainContactsIndexImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainConfidIndexRoute = LayoutmainConfidIndexImport.update({
  id: '/confid/',
  path: '/confid/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainCatalogIndexRoute = LayoutmainCatalogIndexImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainCarzinaIndexRoute = LayoutmainCarzinaIndexImport.update({
  id: '/carzina/',
  path: '/carzina/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainBrendsIndexRoute = LayoutmainBrendsIndexImport.update({
  id: '/brends/',
  path: '/brends/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainAuthIndexRoute = LayoutmainAuthIndexImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainAdminIndexRoute = LayoutmainAdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainAboutUsIndexRoute = LayoutmainAboutUsIndexImport.update({
  id: '/aboutUs/',
  path: '/aboutUs/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainCardinfoCardInfoRoute = LayoutmainCardinfoCardInfoImport.update(
  {
    id: '/cardinfo/cardInfo',
    path: '/cardinfo/cardInfo',
    getParentRoute: () => LayoutmainRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layoutmain': {
      id: '/_layoutmain'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutmainImport
      parentRoute: typeof rootRoute
    }
    '/_layoutmain/cardinfo/cardInfo': {
      id: '/_layoutmain/cardinfo/cardInfo'
      path: '/cardinfo/cardInfo'
      fullPath: '/cardinfo/cardInfo'
      preLoaderRoute: typeof LayoutmainCardinfoCardInfoImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/aboutUs/': {
      id: '/_layoutmain/aboutUs/'
      path: '/aboutUs'
      fullPath: '/aboutUs'
      preLoaderRoute: typeof LayoutmainAboutUsIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/admin/': {
      id: '/_layoutmain/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutmainAdminIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/auth/': {
      id: '/_layoutmain/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof LayoutmainAuthIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/brends/': {
      id: '/_layoutmain/brends/'
      path: '/brends'
      fullPath: '/brends'
      preLoaderRoute: typeof LayoutmainBrendsIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/carzina/': {
      id: '/_layoutmain/carzina/'
      path: '/carzina'
      fullPath: '/carzina'
      preLoaderRoute: typeof LayoutmainCarzinaIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/catalog/': {
      id: '/_layoutmain/catalog/'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof LayoutmainCatalogIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/confid/': {
      id: '/_layoutmain/confid/'
      path: '/confid'
      fullPath: '/confid'
      preLoaderRoute: typeof LayoutmainConfidIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/contacts/': {
      id: '/_layoutmain/contacts/'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof LayoutmainContactsIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/dostavka/': {
      id: '/_layoutmain/dostavka/'
      path: '/dostavka'
      fullPath: '/dostavka'
      preLoaderRoute: typeof LayoutmainDostavkaIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/oferta/': {
      id: '/_layoutmain/oferta/'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof LayoutmainOfertaIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/oformlenie/': {
      id: '/_layoutmain/oformlenie/'
      path: '/oformlenie'
      fullPath: '/oformlenie'
      preLoaderRoute: typeof LayoutmainOformlenieIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/pay/': {
      id: '/_layoutmain/pay/'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof LayoutmainPayIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/profile/': {
      id: '/_layoutmain/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutmainProfileIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/reg/': {
      id: '/_layoutmain/reg/'
      path: '/reg'
      fullPath: '/reg'
      preLoaderRoute: typeof LayoutmainRegIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/sogl/': {
      id: '/_layoutmain/sogl/'
      path: '/sogl'
      fullPath: '/sogl'
      preLoaderRoute: typeof LayoutmainSoglIndexImport
      parentRoute: typeof LayoutmainImport
    }
  }
}

// Create and export the route tree

interface LayoutmainRouteChildren {
  LayoutmainCardinfoCardInfoRoute: typeof LayoutmainCardinfoCardInfoRoute
  LayoutmainAboutUsIndexRoute: typeof LayoutmainAboutUsIndexRoute
  LayoutmainAdminIndexRoute: typeof LayoutmainAdminIndexRoute
  LayoutmainAuthIndexRoute: typeof LayoutmainAuthIndexRoute
  LayoutmainBrendsIndexRoute: typeof LayoutmainBrendsIndexRoute
  LayoutmainCarzinaIndexRoute: typeof LayoutmainCarzinaIndexRoute
  LayoutmainCatalogIndexRoute: typeof LayoutmainCatalogIndexRoute
  LayoutmainConfidIndexRoute: typeof LayoutmainConfidIndexRoute
  LayoutmainContactsIndexRoute: typeof LayoutmainContactsIndexRoute
  LayoutmainDostavkaIndexRoute: typeof LayoutmainDostavkaIndexRoute
  LayoutmainOfertaIndexRoute: typeof LayoutmainOfertaIndexRoute
  LayoutmainOformlenieIndexRoute: typeof LayoutmainOformlenieIndexRoute
  LayoutmainPayIndexRoute: typeof LayoutmainPayIndexRoute
  LayoutmainProfileIndexRoute: typeof LayoutmainProfileIndexRoute
  LayoutmainRegIndexRoute: typeof LayoutmainRegIndexRoute
  LayoutmainSoglIndexRoute: typeof LayoutmainSoglIndexRoute
}

const LayoutmainRouteChildren: LayoutmainRouteChildren = {
  LayoutmainCardinfoCardInfoRoute: LayoutmainCardinfoCardInfoRoute,
  LayoutmainAboutUsIndexRoute: LayoutmainAboutUsIndexRoute,
  LayoutmainAdminIndexRoute: LayoutmainAdminIndexRoute,
  LayoutmainAuthIndexRoute: LayoutmainAuthIndexRoute,
  LayoutmainBrendsIndexRoute: LayoutmainBrendsIndexRoute,
  LayoutmainCarzinaIndexRoute: LayoutmainCarzinaIndexRoute,
  LayoutmainCatalogIndexRoute: LayoutmainCatalogIndexRoute,
  LayoutmainConfidIndexRoute: LayoutmainConfidIndexRoute,
  LayoutmainContactsIndexRoute: LayoutmainContactsIndexRoute,
  LayoutmainDostavkaIndexRoute: LayoutmainDostavkaIndexRoute,
  LayoutmainOfertaIndexRoute: LayoutmainOfertaIndexRoute,
  LayoutmainOformlenieIndexRoute: LayoutmainOformlenieIndexRoute,
  LayoutmainPayIndexRoute: LayoutmainPayIndexRoute,
  LayoutmainProfileIndexRoute: LayoutmainProfileIndexRoute,
  LayoutmainRegIndexRoute: LayoutmainRegIndexRoute,
  LayoutmainSoglIndexRoute: LayoutmainSoglIndexRoute,
}

const LayoutmainRouteWithChildren = LayoutmainRoute._addFileChildren(
  LayoutmainRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutmainRouteWithChildren
  '/cardinfo/cardInfo': typeof LayoutmainCardinfoCardInfoRoute
  '/aboutUs': typeof LayoutmainAboutUsIndexRoute
  '/admin': typeof LayoutmainAdminIndexRoute
  '/auth': typeof LayoutmainAuthIndexRoute
  '/brends': typeof LayoutmainBrendsIndexRoute
  '/carzina': typeof LayoutmainCarzinaIndexRoute
  '/catalog': typeof LayoutmainCatalogIndexRoute
  '/confid': typeof LayoutmainConfidIndexRoute
  '/contacts': typeof LayoutmainContactsIndexRoute
  '/dostavka': typeof LayoutmainDostavkaIndexRoute
  '/oferta': typeof LayoutmainOfertaIndexRoute
  '/oformlenie': typeof LayoutmainOformlenieIndexRoute
  '/pay': typeof LayoutmainPayIndexRoute
  '/profile': typeof LayoutmainProfileIndexRoute
  '/reg': typeof LayoutmainRegIndexRoute
  '/sogl': typeof LayoutmainSoglIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutmainRouteWithChildren
  '/cardinfo/cardInfo': typeof LayoutmainCardinfoCardInfoRoute
  '/aboutUs': typeof LayoutmainAboutUsIndexRoute
  '/admin': typeof LayoutmainAdminIndexRoute
  '/auth': typeof LayoutmainAuthIndexRoute
  '/brends': typeof LayoutmainBrendsIndexRoute
  '/carzina': typeof LayoutmainCarzinaIndexRoute
  '/catalog': typeof LayoutmainCatalogIndexRoute
  '/confid': typeof LayoutmainConfidIndexRoute
  '/contacts': typeof LayoutmainContactsIndexRoute
  '/dostavka': typeof LayoutmainDostavkaIndexRoute
  '/oferta': typeof LayoutmainOfertaIndexRoute
  '/oformlenie': typeof LayoutmainOformlenieIndexRoute
  '/pay': typeof LayoutmainPayIndexRoute
  '/profile': typeof LayoutmainProfileIndexRoute
  '/reg': typeof LayoutmainRegIndexRoute
  '/sogl': typeof LayoutmainSoglIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layoutmain': typeof LayoutmainRouteWithChildren
  '/_layoutmain/cardinfo/cardInfo': typeof LayoutmainCardinfoCardInfoRoute
  '/_layoutmain/aboutUs/': typeof LayoutmainAboutUsIndexRoute
  '/_layoutmain/admin/': typeof LayoutmainAdminIndexRoute
  '/_layoutmain/auth/': typeof LayoutmainAuthIndexRoute
  '/_layoutmain/brends/': typeof LayoutmainBrendsIndexRoute
  '/_layoutmain/carzina/': typeof LayoutmainCarzinaIndexRoute
  '/_layoutmain/catalog/': typeof LayoutmainCatalogIndexRoute
  '/_layoutmain/confid/': typeof LayoutmainConfidIndexRoute
  '/_layoutmain/contacts/': typeof LayoutmainContactsIndexRoute
  '/_layoutmain/dostavka/': typeof LayoutmainDostavkaIndexRoute
  '/_layoutmain/oferta/': typeof LayoutmainOfertaIndexRoute
  '/_layoutmain/oformlenie/': typeof LayoutmainOformlenieIndexRoute
  '/_layoutmain/pay/': typeof LayoutmainPayIndexRoute
  '/_layoutmain/profile/': typeof LayoutmainProfileIndexRoute
  '/_layoutmain/reg/': typeof LayoutmainRegIndexRoute
  '/_layoutmain/sogl/': typeof LayoutmainSoglIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/cardinfo/cardInfo'
    | '/aboutUs'
    | '/admin'
    | '/auth'
    | '/brends'
    | '/carzina'
    | '/catalog'
    | '/confid'
    | '/contacts'
    | '/dostavka'
    | '/oferta'
    | '/oformlenie'
    | '/pay'
    | '/profile'
    | '/reg'
    | '/sogl'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/cardinfo/cardInfo'
    | '/aboutUs'
    | '/admin'
    | '/auth'
    | '/brends'
    | '/carzina'
    | '/catalog'
    | '/confid'
    | '/contacts'
    | '/dostavka'
    | '/oferta'
    | '/oformlenie'
    | '/pay'
    | '/profile'
    | '/reg'
    | '/sogl'
  id:
    | '__root__'
    | '/'
    | '/_layoutmain'
    | '/_layoutmain/cardinfo/cardInfo'
    | '/_layoutmain/aboutUs/'
    | '/_layoutmain/admin/'
    | '/_layoutmain/auth/'
    | '/_layoutmain/brends/'
    | '/_layoutmain/carzina/'
    | '/_layoutmain/catalog/'
    | '/_layoutmain/confid/'
    | '/_layoutmain/contacts/'
    | '/_layoutmain/dostavka/'
    | '/_layoutmain/oferta/'
    | '/_layoutmain/oformlenie/'
    | '/_layoutmain/pay/'
    | '/_layoutmain/profile/'
    | '/_layoutmain/reg/'
    | '/_layoutmain/sogl/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutmainRoute: typeof LayoutmainRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutmainRoute: LayoutmainRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/_layoutmain"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/_layoutmain": {
      "filePath": "_layoutmain.jsx",
      "children": [
        "/_layoutmain/cardinfo/cardInfo",
        "/_layoutmain/aboutUs/",
        "/_layoutmain/admin/",
        "/_layoutmain/auth/",
        "/_layoutmain/brends/",
        "/_layoutmain/carzina/",
        "/_layoutmain/catalog/",
        "/_layoutmain/confid/",
        "/_layoutmain/contacts/",
        "/_layoutmain/dostavka/",
        "/_layoutmain/oferta/",
        "/_layoutmain/oformlenie/",
        "/_layoutmain/pay/",
        "/_layoutmain/profile/",
        "/_layoutmain/reg/",
        "/_layoutmain/sogl/"
      ]
    },
    "/_layoutmain/cardinfo/cardInfo": {
      "filePath": "_layoutmain/cardinfo/cardInfo.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/aboutUs/": {
      "filePath": "_layoutmain/aboutUs/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/admin/": {
      "filePath": "_layoutmain/admin/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/auth/": {
      "filePath": "_layoutmain/auth/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/brends/": {
      "filePath": "_layoutmain/brends/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/carzina/": {
      "filePath": "_layoutmain/carzina/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/catalog/": {
      "filePath": "_layoutmain/catalog/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/confid/": {
      "filePath": "_layoutmain/confid/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/contacts/": {
      "filePath": "_layoutmain/contacts/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/dostavka/": {
      "filePath": "_layoutmain/dostavka/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/oferta/": {
      "filePath": "_layoutmain/oferta/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/oformlenie/": {
      "filePath": "_layoutmain/oformlenie/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/pay/": {
      "filePath": "_layoutmain/pay/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/profile/": {
      "filePath": "_layoutmain/profile/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/reg/": {
      "filePath": "_layoutmain/reg/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/sogl/": {
      "filePath": "_layoutmain/sogl/index.jsx",
      "parent": "/_layoutmain"
    }
  }
}
ROUTE_MANIFEST_END */
