/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutmainImport } from './routes/_layoutmain'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutmainSoglIndexImport } from './routes/_layoutmain/sogl/index'
import { Route as LayoutmainPayIndexImport } from './routes/_layoutmain/pay/index'
import { Route as LayoutmainOfertaIndexImport } from './routes/_layoutmain/oferta/index'
import { Route as LayoutmainContactsIndexImport } from './routes/_layoutmain/contacts/index'
import { Route as LayoutmainConfidIndexImport } from './routes/_layoutmain/confid/index'
import { Route as LayoutmainBrendsIndexImport } from './routes/_layoutmain/brends/index'
import { Route as LayoutmainAboutUsIndexImport } from './routes/_layoutmain/aboutUs/index'

// Create/Update Routes

const LayoutmainRoute = LayoutmainImport.update({
  id: '/_layoutmain',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutmainSoglIndexRoute = LayoutmainSoglIndexImport.update({
  id: '/sogl/',
  path: '/sogl/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainPayIndexRoute = LayoutmainPayIndexImport.update({
  id: '/pay/',
  path: '/pay/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainOfertaIndexRoute = LayoutmainOfertaIndexImport.update({
  id: '/oferta/',
  path: '/oferta/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainContactsIndexRoute = LayoutmainContactsIndexImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainConfidIndexRoute = LayoutmainConfidIndexImport.update({
  id: '/confid/',
  path: '/confid/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainBrendsIndexRoute = LayoutmainBrendsIndexImport.update({
  id: '/brends/',
  path: '/brends/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainAboutUsIndexRoute = LayoutmainAboutUsIndexImport.update({
  id: '/aboutUs/',
  path: '/aboutUs/',
  getParentRoute: () => LayoutmainRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layoutmain': {
      id: '/_layoutmain'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutmainImport
      parentRoute: typeof rootRoute
    }
    '/_layoutmain/aboutUs/': {
      id: '/_layoutmain/aboutUs/'
      path: '/aboutUs'
      fullPath: '/aboutUs'
      preLoaderRoute: typeof LayoutmainAboutUsIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/brends/': {
      id: '/_layoutmain/brends/'
      path: '/brends'
      fullPath: '/brends'
      preLoaderRoute: typeof LayoutmainBrendsIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/confid/': {
      id: '/_layoutmain/confid/'
      path: '/confid'
      fullPath: '/confid'
      preLoaderRoute: typeof LayoutmainConfidIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/contacts/': {
      id: '/_layoutmain/contacts/'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof LayoutmainContactsIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/oferta/': {
      id: '/_layoutmain/oferta/'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof LayoutmainOfertaIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/pay/': {
      id: '/_layoutmain/pay/'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof LayoutmainPayIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/sogl/': {
      id: '/_layoutmain/sogl/'
      path: '/sogl'
      fullPath: '/sogl'
      preLoaderRoute: typeof LayoutmainSoglIndexImport
      parentRoute: typeof LayoutmainImport
    }
  }
}

// Create and export the route tree

interface LayoutmainRouteChildren {
  LayoutmainAboutUsIndexRoute: typeof LayoutmainAboutUsIndexRoute
  LayoutmainBrendsIndexRoute: typeof LayoutmainBrendsIndexRoute
  LayoutmainConfidIndexRoute: typeof LayoutmainConfidIndexRoute
  LayoutmainContactsIndexRoute: typeof LayoutmainContactsIndexRoute
  LayoutmainOfertaIndexRoute: typeof LayoutmainOfertaIndexRoute
  LayoutmainPayIndexRoute: typeof LayoutmainPayIndexRoute
  LayoutmainSoglIndexRoute: typeof LayoutmainSoglIndexRoute
}

const LayoutmainRouteChildren: LayoutmainRouteChildren = {
  LayoutmainAboutUsIndexRoute: LayoutmainAboutUsIndexRoute,
  LayoutmainBrendsIndexRoute: LayoutmainBrendsIndexRoute,
  LayoutmainConfidIndexRoute: LayoutmainConfidIndexRoute,
  LayoutmainContactsIndexRoute: LayoutmainContactsIndexRoute,
  LayoutmainOfertaIndexRoute: LayoutmainOfertaIndexRoute,
  LayoutmainPayIndexRoute: LayoutmainPayIndexRoute,
  LayoutmainSoglIndexRoute: LayoutmainSoglIndexRoute,
}

const LayoutmainRouteWithChildren = LayoutmainRoute._addFileChildren(
  LayoutmainRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutmainRouteWithChildren
  '/aboutUs': typeof LayoutmainAboutUsIndexRoute
  '/brends': typeof LayoutmainBrendsIndexRoute
  '/confid': typeof LayoutmainConfidIndexRoute
  '/contacts': typeof LayoutmainContactsIndexRoute
  '/oferta': typeof LayoutmainOfertaIndexRoute
  '/pay': typeof LayoutmainPayIndexRoute
  '/sogl': typeof LayoutmainSoglIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutmainRouteWithChildren
  '/aboutUs': typeof LayoutmainAboutUsIndexRoute
  '/brends': typeof LayoutmainBrendsIndexRoute
  '/confid': typeof LayoutmainConfidIndexRoute
  '/contacts': typeof LayoutmainContactsIndexRoute
  '/oferta': typeof LayoutmainOfertaIndexRoute
  '/pay': typeof LayoutmainPayIndexRoute
  '/sogl': typeof LayoutmainSoglIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layoutmain': typeof LayoutmainRouteWithChildren
  '/_layoutmain/aboutUs/': typeof LayoutmainAboutUsIndexRoute
  '/_layoutmain/brends/': typeof LayoutmainBrendsIndexRoute
  '/_layoutmain/confid/': typeof LayoutmainConfidIndexRoute
  '/_layoutmain/contacts/': typeof LayoutmainContactsIndexRoute
  '/_layoutmain/oferta/': typeof LayoutmainOfertaIndexRoute
  '/_layoutmain/pay/': typeof LayoutmainPayIndexRoute
  '/_layoutmain/sogl/': typeof LayoutmainSoglIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/aboutUs'
    | '/brends'
    | '/confid'
    | '/contacts'
    | '/oferta'
    | '/pay'
    | '/sogl'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/aboutUs'
    | '/brends'
    | '/confid'
    | '/contacts'
    | '/oferta'
    | '/pay'
    | '/sogl'
  id:
    | '__root__'
    | '/'
    | '/_layoutmain'
    | '/_layoutmain/aboutUs/'
    | '/_layoutmain/brends/'
    | '/_layoutmain/confid/'
    | '/_layoutmain/contacts/'
    | '/_layoutmain/oferta/'
    | '/_layoutmain/pay/'
    | '/_layoutmain/sogl/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutmainRoute: typeof LayoutmainRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutmainRoute: LayoutmainRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/_layoutmain"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/_layoutmain": {
      "filePath": "_layoutmain.jsx",
      "children": [
        "/_layoutmain/aboutUs/",
        "/_layoutmain/brends/",
        "/_layoutmain/confid/",
        "/_layoutmain/contacts/",
        "/_layoutmain/oferta/",
        "/_layoutmain/pay/",
        "/_layoutmain/sogl/"
      ]
    },
    "/_layoutmain/aboutUs/": {
      "filePath": "_layoutmain/aboutUs/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/brends/": {
      "filePath": "_layoutmain/brends/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/confid/": {
      "filePath": "_layoutmain/confid/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/contacts/": {
      "filePath": "_layoutmain/contacts/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/oferta/": {
      "filePath": "_layoutmain/oferta/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/pay/": {
      "filePath": "_layoutmain/pay/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/sogl/": {
      "filePath": "_layoutmain/sogl/index.jsx",
      "parent": "/_layoutmain"
    }
  }
}
ROUTE_MANIFEST_END */
